nodeLinker: pnp

npmScopes:
  fuks-ru:
    npmAuthToken: "${PERSONAL_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@nestjs-modules/mailer@*":
    dependencies:
      lodash: "*"
      tslib: "*"
  "@rtk-query/codegen-openapi@*":
    dependencies:
      lodash: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
