name: 'Run node container'
description: 'Run node container'
inputs:
  script:
    description: 'Script for run'
    required: true
  detached:
    description: 'Detached docker mode'
    required: false
  secret-context:
    description: 'Secret params'
    required: true
  domain:
    description: 'Domain url'
    required: true
  backend-container:
    description: 'Backend container name'
    required: true
  postgres-container:
    description: 'Postgres container name'
    required: true
  telegram-bot:
    description: 'Telegram bot name'
    required: true
  telegram-bot-token:
    description: 'Telegram bot token'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ fromJson(inputs.secret-context).SSH_HOST }}
        username: ${{ fromJson(inputs.secret-context).SSH_NODE_USERNAME }}
        key: ${{ fromJson(inputs.secret-context).SSH_NODE_PRIVATE_KEY }}
        script: |
          docker run --name ${{ inputs.backend-container }} \
          --rm ${{ inputs.detached && '-d' }} \
          -e POSTGRES_PASSWORD="${{ fromJson(inputs.secret-context).POSTGRES_PASSWORD }}" \
          -e POSTGRES_USER="${{ fromJson(inputs.secret-context).POSTGRES_USER }}" \
          -e POSTGRES_HOST="${{ inputs.postgres-container }}" \
          -e GOOGLE_AUTH_CLIENT_ID="${{ fromJson(inputs.secret-context).GOOGLE_AUTH_CLIENT_ID }}" \
          -e GOOGLE_RECAPTCHA_SECRET_KEY="${{ fromJson(inputs.secret-context).GOOGLE_RECAPTCHA_SECRET_KEY }}" \
          -e JWT_SECRET="${{ fromJson(inputs.secret-context).JWT_SECRET }}" \
          -e PERSONAL_NPM_TOKEN="${{ fromJson(inputs.secret-context).PERSONAL_TOKEN }}" \
          -e MAILER_USER="${{ fromJson(inputs.secret-context).MAILER_USER }}" \
          -e MAILER_PASSWORD="${{ fromJson(inputs.secret-context).MAILER_PASSWORD }}" \
          -e MAILER_HOST="${{ fromJson(inputs.secret-context).MAILER_HOST }}" \
          -e ZADARMA_SECRET_KEY="${{ fromJson(inputs.secret-context).ZADARMA_SECRET_KEY }}" \
          -e ZADARMA_USER_KEY="${{ fromJson(inputs.secret-context).ZADARMA_USER_KEY }}" \
          -e ZADARMA_CALLER_ID="${{ fromJson(inputs.secret-context).ZADARMA_CALLER_ID }}" \
          -e INTERNAL_REQUEST_TOKEN="${{ fromJson(inputs.secret-context).INTERNAL_REQUEST_TOKEN }}" \
          -e DOMAIN="${{ inputs.domain }}" \
          -e TELEGRAM_BOT_NAME="${{ inputs.telegram-bot }}" \
          -e TELEGRAM_BOT_TOKEN="${{ inputs.telegram-bot-token }}" \
          -v "/server/${{ inputs.backend-container }}/backend/var":/app/entries/backend/var \
          --network="fuks-ru" \
          difuks/auth \
          ${{ inputs.script }}
